### ISSUE TITLE
Can't open saves.

### ISSUE THREAD

**Issue by deepy** [seefo/PD2SaveEditor#1]
Neither using encrypted or decrypted opens a save or gives any notification.

**Comment by JanWerder** [comment]
I can confirm that

**Comment by rohvani** [comment]
I have gone ahead and updated this tool to support the retail version of PAYDAY 2.  I know this is a bit late, but hopefully anyone else searching for this may use it.  You may find a zip of the executable under the releases section (https://github.com/seefo/PD2SaveEditor/releases).
